/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AddressesImport } from "./routes/$addresses";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const AddressesRoute = AddressesImport.update({
  id: "/$addresses",
  path: "/$addresses",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/$addresses": {
      id: "/$addresses";
      path: "/$addresses";
      fullPath: "/$addresses";
      preLoaderRoute: typeof AddressesImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$addresses": typeof AddressesRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$addresses": typeof AddressesRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/$addresses": typeof AddressesRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$addresses";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$addresses";
  id: "__root__" | "/" | "/$addresses";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AddressesRoute: typeof AddressesRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$addresses"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$addresses": {
      "filePath": "$addresses.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
