/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AddressImport } from "./routes/$address";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const AddressRoute = AddressImport.update({
  id: "/$address",
  path: "/$address",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/$address": {
      id: "/$address";
      path: "/$address";
      fullPath: "/$address";
      preLoaderRoute: typeof AddressImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$address": typeof AddressRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$address": typeof AddressRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/$address": typeof AddressRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$address";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$address";
  id: "__root__" | "/" | "/$address";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AddressRoute: typeof AddressRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRoute: AddressRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$address"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$address": {
      "filePath": "$address.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
